### ISSUE TITLE
好像不支持fish_redux v0.2.0以上版本

### ISSUE THREAD

**Issue by a314730500** [blankapp/flutter_flipperkit#11]
Because flipperkit_fish_redux_middleware 0.0.2 depends on fish_redux ^0.1.2 and no versions of flipperkit_fish_redux_middleware match >0.0.2 <0.1.0, flipperkit_fish_redux_middleware ^0.0.2 requires fish_redux ^0.1.2.
。。。。。

pub get failed (1)

**Comment by lijy91** [comment]
已修复，请更新 `flipperkit_fish_redux_middleware` 到 0.0.3

```
flipperkit_fish_redux_middleware: ^0.0.3
```

示例已更新：https://github.com/blankapp/fish_redux_example

**Comment by hfbi360** [comment]
fish_redux已更新到0.3.1了，这个版本又不支持了

**Comment by lijy91** [comment]
@hfbi360

已支持 0.3.1，请更新 `flipperkit_fish_redux_middleware` 到 0.0.4

```
flipperkit_fish_redux_middleware: ^0.0.4
```

示例已更新：https://github.com/blankapp/flutter_flipperkit_examples/tree/master/fish_redux_example
