### ISSUE TITLE
Flutter升级1.7 之后  ios 运行不起来

### ISSUE THREAD

**Issue by LZQL** [blankapp/flutter_flipperkit#16]
Resolving dependencies of 'PodFile'
[!] CocoaPods could not find compatible versions for pod "FlipperKit/FlipperKitLayoutComponentKitSupport":

**Comment by LZQL** [comment]
只要 删掉 podfile.lock 重新 run 就可以了，在此之前，有可能需要pod repo update

**Comment by lijy91** [comment]
Please delete the `ios/Podfile.lock` file.
