### ISSUE TITLE
flutter_flipperkit 和 multi_image_picker 和 flutter_inappbrowser  在一起 跑不起来

### ISSUE THREAD

**Issue by LZQL** [blankapp/flutter_flipperkit#18]
最简单的demo 就是 在 pubspec.yaml 中 引入

```
 multi_image_picker: ^4.4.0
  flutter_flipperkit: ^0.0.19
  flutter_inappbrowser: ^1.2.1
```

ios 运行不起来，如果是  只有multi_image_picker 和 flutter_inappbrowser 是可以的

**Comment by lijy91** [comment]
目前检查下来是由于两个SWIF版本不一致导致的，建议可以切换 webview 插件为 https://pub.flutter-io.cn/packages/webview_flutter
