### ISSUE TITLE
Link error when building app for ios

### ISSUE THREAD

**Issue by kaciula** [blankapp/flutter_flipperkit#19]
Hi.

I can't build my flutter app for ios. I get tons of link errors for Flipper-Folly. Can you help me out? (Everything works perfectly on Android)

I don't know what part of the error messages to put here. I have zero experience with ios.

```
Undefined symbols for architecture x86_64:
  "boost::re_detail_106300::perl_matcher<char const*, std::__1::allocator<boost::sub_match<char const*> >, boost::regex_traits<char, boost::cpp_regex_traits<char> > >::find()", referenced from:
      bool boost::regex_search<char const*, std::__1::allocator<boost::sub_match<char const*> >, char, 
```

**Comment by lijy91** [comment]
You can upgrade `flutter_flipperkit` to `0.0.20` and refer to this answer.
https://stackoverflow.com/a/56176956
