### ISSUE TITLE
有Demo吗 ？看不了啊

### ISSUE THREAD

**Issue by SilenceZhou** [blankapp/flutter_flipperkit#2]

**Comment by lijy91** [comment]
这是 Dio 2.0 的示例，请将示例中的 flipper_dio_interceptor.dart 文件添加到你的项目
https://github.com/blankapp/flutter_flipperkit/blob/master/example/lib/networking/api_client/api_client.dart

```
BaseOptions options = new BaseOptions(
      baseUrl: 'https://www.v2ex.com/api',
      connectTimeout: 5000,
      receiveTimeout: 3000,
      headers: {
        "Accept": "application/json",
        "Content-Type": "application/json"
      },
      responseType: ResponseType.json,
    );
    this._http = new Dio(options);
    // 添加 FlipperDioInterceptor 拦截器
    this._http.interceptors.add(FlipperDioInterceptor());
```

**Comment by zakiso** [comment]
只有使用dio做为网络请求客户端的时候 才能用吗？

**Comment by lijy91** [comment]
@zakiso `flutter_flipperkit` (将在 0.0.7 中发布该功能，请留意版本更新) 已支持全局拦截网络请求（所有基于 `HttpClient` API 的请求均可被拦截），如果你未设置网络插件 `useHttpOverrides` 参数为 false，则无需使用该拦截器。

如果其他网络请求库无法被自动拦截，则可能参考 Dio 的实现。
https://github.com/blankapp/flutter_flipperkit_plugins/tree/master/packages/flipperkit_dio_interceptor

如有疑问可加入电报群 https://t.me/flutterdebugger 提问。

**Comment by zakiso** [comment]
👍 期待新版本

**Comment by lijy91** [comment]
@zakiso Flutter Debugger 已经发布，
下载：https://github.com/blankapp/flutter-debugger/releases/
文档：https://flutter-debugger.blankapp.org/
