### ISSUE TITLE
One line missing in docs

### ISSUE THREAD

**Issue by vasilich6107** [blankapp/flutter_flipperkit#21]
Hi. Thanks for your work
There is a little update for successful launch.

You'll need to add one line at the top of the main fn `WidgetsFlutterBinding.ensureInitialized();`

```
void main() {
  // add the next line missing in docs
  WidgetsFlutterBinding.ensureInitialized();

  FlipperClient flipperClient = FlipperClient.getDefault();
  // ...
  // all other init code from docs

  runApp(MyApp());
}
```

**Comment by lijy91** [comment]
I don't think this is due to a problem caused by `flutter_flipperkit`, you can search https://github.com/flutter/flutter/search?q=WidgetsFlutterBinding.ensureInitialized&type=Issues

**Comment by lijy91** [comment]
The example does not add the line, but it is working fine.

https://github.com/blankapp/flutter_flipperkit/tree/master/example
