### ISSUE TITLE
Completely ignore iOS side at will

### ISSUE THREAD

**Issue by tommiperttila** [blankapp/flutter_flipperkit#23]
The iOS side implementation seems to be full of problems, can we completely ignore the iOS somehow?

**Comment by lijy91** [comment]
What is the problem? Maybe you should fork the repo and remove the ios related code.

**Comment by tommiperttila** [comment]
I am talking about:
https://github.com/blankapp/flutter_flipperkit/issues/10
https://github.com/facebook/flipper/issues/478
https://github.com/facebook/flipper/issues/254#issuecomment-504405955

Which all are closed issues with suggestions doing changes to Podfile and/or downgrading CocoaPods that I can't get to work in my specific configuration.
