### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method clientAddPlugin on channel flutter_flipperkit)

### ISSUE THREAD

**Issue by royibernthal** [blankapp/flutter_flipperkit#25]
I tried following the quick start here:
https://pub.dev/packages/flutter_flipperkit#quick-start

Android Emulator Pixel 3 API 28, Pie

Using the latest flutter version.

I keep getting an error:

> E/flutter ( 9165): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method clientAddPlugin on channel flutter_flipperkit)
> E/flutter ( 9165): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> E/flutter ( 9165): <asynchronous suspension>
> E/flutter ( 9165): #1      FlipperClient.addPlugin (package:flutter_flipperkit/flipper_client.dart:24:20)
> E/flutter ( 9165): #2      initFlipper (package:matchmaking_app/main.dart:22:17)
> E/flutter ( 9165): #3      main (package:matchmaking_app/main.dart:11:3)
> E/flutter ( 9165): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
> E/flutter ( 9165): #5      _rootRun (dart:async/zone.dart:1126:13)
> E/flutter ( 9165): #6      _CustomZone.run (dart:async/zone.dart:1023:19)
> E/flutter ( 9165): #7      _runZoned (dart:async/zone.dart:1518:10)
> E/flutter ( 9165): #8      runZoned (dart:async/zone.dart:1502:12)
> E/flutter ( 9165): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
> E/flutter ( 9165): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
> E/flutter ( 9165): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> E/flutter ( 9165): 
> E/flutter ( 9165): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method clientAddPlugin on channel flutter_flipperkit)
> E/flutter ( 9165): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> E/flutter ( 9165): <asynchronous suspension>
> E/flutter ( 9165): #1      FlipperClient.addPlugin (package:flutter_flipperkit/flipper_client.dart:24:20)
> E/flutter ( 9165): #2      initFlipper (package:matchmaking_app/main.dart:23:17)
> E/flutter ( 9165): #3      main (package:matchmaking_app/main.dart:11:3)
> E/flutter ( 9165): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
> E/flutter ( 9165): #5      _rootRun (dart:async/zone.dart:1126:13)
> E/flutter ( 9165): #6      _CustomZone.run (dart:async/zone.dart:1023:19)
> E/flutter ( 9165): #7      _runZoned (dart:async/zone.dart:1518:10)
> E/flutter ( 9165): #8      runZoned (dart:async/zone.dart:1502:12)
> E/flutter ( 9165): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
> E/flutter ( 9165): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
> E/flutter ( 9165): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> E/flutter ( 9165): 
> E/flutter ( 9165): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method clientAddPlugin on channel flutter_flipperkit)
> E/flutter ( 9165): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> E/flutter ( 9165): <asynchronous suspension>
> E/flutter ( 9165): #1      FlipperClient.addPlugin (package:flutter_flipperkit/flipper_client.dart:24:20)
> E/flutter ( 9165): #2      initFlipper (package:matchmaking_app/main.dart:24:17)
> E/flutter ( 9165): #3      main (package:matchmaking_app/main.dart:11:3)
> E/flutter ( 9165): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
> E/flutter ( 9165): #5      _rootRun (dart:async/zone.dart:1126:13)
> E/flutter ( 9165): #6      _CustomZone.run (dart:async/zone.dart:1023:19)
> E/flutter ( 9165): #7      _runZoned (dart:async/zone.dart:1518:10)
> E/flutter ( 9165): #8      runZoned (dart:async/zone.dart:1502:12)
> E/flutter ( 9165): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
> E/flutter ( 9165): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
> E/flutter ( 9165): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> E/flutter ( 9165): 
> E/flutter ( 9165): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method clientStart on channel flutter_flipperkit)
> E/flutter ( 9165): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
> E/flutter ( 9165): <asynchronous suspension>
> E/flutter ( 9165): #1      FlipperClient.start (package:flutter_flipperkit/flipper_client.dart:36:20)
> E/flutter ( 9165): #2      initFlipper (package:matchmaking_app/main.dart:25:17)
> E/flutter ( 9165): #3      main (package:matchmaking_app/main.dart:11:3)
> E/flutter ( 9165): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
> E/flutter ( 9165): #5      _rootRun (dart:async/zone.dart:1126:13)
> E/flutter ( 9165): #6      _CustomZone.run (dart:async/zone.dart:1023:19)
> E/flutter ( 9165): #7      _runZoned (dart:async/zone.dart:1518:10)
> E/flutter ( 9165): #8      runZoned (dart:async/zone.dart:1502:12)
> E/flutter ( 9165): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
> E/flutter ( 9165): #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
> E/flutter ( 9165): #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> E/flutter ( 9165): 

Screenshot:
![ss](https://user-images.githubusercontent.com/7274413/71626421-0278b300-2c28-11ea-9ac6-0ac0ae01ce0b.png)

**Comment by lijy91** [comment]
https://github.com/facebook/flipper/issues/707#issuecomment-573092858

Flipper may not yet support the Android emulator
