### ISSUE TITLE
Error building iOS app after Flutter (1.22.1) upgrade

### ISSUE THREAD

**Issue by Twinsen81** [blankapp/flutter_flipperkit#32]
I get the following output after upgrading to Flutter 1.22.1 (flutter_flipperkit: 0.0.24):

While building module 'Flipper' imported from /Users/user/Projects/Flutter/sbp/ios/Pods/Headers/Public/FlipperKit/FlipperKitCertificateProvider.h:10:
    In file included from <module-includes>:1:
    In file included from /Users/user/Projects/Flutter/sbp/ios/Pods/Headers/Public/Flipper/Flipper-umbrella.h:14:
    In file included from /Users/user/Projects/Flutter/sbp/ios/Pods/Headers/Public/Flipper/ConnectionContextStore.h:10:
    /Users/user/Projects/Flutter/sbp/ios/Pods/Headers/Public/Flipper-Folly/folly/dynamic.h:55:10: fatal error: 'cstdint' file not found
    #include <cstdint>
             ^~~~~~~~~
    1 error generated.
    While building module 'flutter_flipperkit' imported from /Users/user/Projects/Flutter/sbp/ios/Runner/GeneratedPluginRegistrant.m:38:
    While building module 'FlipperKit' imported from /Users/user/Projects/Flutter/sbp/build/ios/Debug-iphoneos/flutter_flipperkit/flutter_flipperkit.framework/Headers/FlipperDatabaseBrowserPlugin.h:2:
    In file included from <module-includes>:1:
    In file included from /Users/user/Projects/Flutter/sbp/ios/Pods/Headers/Public/FlipperKit/FlipperKit-umbrella.h:13:
    In file included from /Users/user/Projects/Flutter/sbp/ios/Pods/Headers/Public/FlipperKit/FlipperClient.h:11:
    /Users/user/Projects/Flutter/sbp/ios/Pods/Headers/Public/FlipperKit/FlipperKitCertificateProvider.h:10:9: fatal error: could not build module 'Flipper'
    #import <Flipper/FlipperCertificateExchangeMedium.h>
     ~~~~~~~^
    2 errors generated.
    While building module 'flutter_flipperkit' imported from /Users/user/Projects/Flutter/sbp/ios/Runner/GeneratedPluginRegistrant.m:38:
    In file included from <module-includes>:1:
    In file included from /Users/user/Projects/Flutter/sbp/build/ios/Debug-iphoneos/flutter_flipperkit/flutter_flipperkit.framework/Headers/flutter_flipperkit-umbrella.h:14:
    /Users/user/Projects/Flutter/sbp/build/ios/Debug-iphoneos/flutter_flipperkit/flutter_flipperkit.framework/Headers/FlipperDatabaseBrowserPlugin.h:2:9: fatal error: could not build module 'FlipperKit'
    #import <FlipperKit/FlipperPlugin.h>
     ~~~~~~~^
    3 errors generated.
    /Users/user/Projects/Flutter/sbp/ios/Runner/GeneratedPluginRegistrant.m:38:9: fatal error: could not build module 'flutter_flipperkit'
    #import <flutter_flipperkit/FlutterFlipperkitPlugin.h>
     ~~~~~~~^
    4 errors generated.
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: no rule to process file '/Users/user/Projects/Flutter/sbp/ios/Pods/ComponentKit/ComponentKit/ComponentKit.xcconfig' of type 'text.xcconfig' for architecture 'arm64' (in target 'ComponentKit' from project 'Pods')
    warning: no rule to process file '/Users/user/Projects/Flutter/sbp/ios/Pods/Flipper-RSocket/rsocket/benchmarks/CMakeLists.txt' of type 'text' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')
    warning: no rule to process file '/Users/user/Projects/Flutter/sbp/ios/Pods/Flipper-RSocket/rsocket/benchmarks/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')
    warning: no rule to process file '/Users/user/Projects/Flutter/sbp/ios/Pods/Flipper-RSocket/rsocket/README.md' of type 'net.daringfireball.markdown' for architecture 'arm64' (in target 'Flipper-RSocket' from project 'Pods')

**Comment by lijy91** [comment]
You can try this step
> Open ios/Runner.xcworkspace Add a empty Swift file (e.g Runner-Noop.swift) into Runner Group And make sure the Runner-Bridging-Header.h file is created.

**Comment by Twinsen81** [comment]
Tried that - doesn't help, unfortunately (

**Comment by lijy91** [comment]
Can you push your code to github?

**Comment by Twinsen81** [comment]
Unfortunately I can't - it's a commercial app. It worked fine before the Flutter update. When I remove Flipper from the project, then the iOS app builds successfully.

**Comment by Twinsen81** [comment]
I'll create a test app from scratch later to see if this is the problem with my MacOS/XCode/Flutter config.

**Comment by lijy91** [comment]
Are you run it in debug mode?

**Comment by Twinsen81** [comment]
yes

**Comment by lijy91** [comment]
Can you put your dependencies?

**Comment by Twinsen81** [comment]
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^0.5.0
  firebase_analytics: 6.0.0
  firebase_crashlytics: 0.1.4+1

  injectable: 1.0.4
  get_it: 4.0.4
  provider: 4.3.2

  connectivity: 0.4.9+5
  dio: 3.0.10
  retrofit: 1.3.4
  flutter_flipperkit: ^0.0.24
  json_serializable: 3.4.0
  freezed_annotation:
  cached_network_image:

  cupertino_icons: 0.1.3
  flutter_fimber: 0.4.4
  mockito: 4.1.1
  introduction_screen: ^1.0.9
  webview_flutter: 1.0.3
  flutter_secure_storage: 3.3.3
  shared_preferences: ^0.5.12
  flutter_svg: 0.18.0
  easy_localization: 2.3.3
  qr_flutter: ^3.1.0
  decimal: 0.3.5
  url_launcher:
  sticky_headers: ^0.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  retrofit_generator: 1.3.7+5
  freezed:

  injectable_generator: 1.0.4
  build_runner: 1.10.1

  flutter_launcher_icons: "^0.8.0"

**Comment by Twinsen81** [comment]
Have the same issue with an app built from scratch: https://github.com/Twinsen81/flutter_mishap

**Comment by Twinsen81** [comment]
XCode Version 11.7 (11E801a)

**Comment by lijy91** [comment]
@Twinsen81  When I delete `use_modular_headers!` (`/ios/Podfile` file), build successful.

**Comment by Twinsen81** [comment]
Yes, that solves the problem! Thank you very much!
