### ISSUE TITLE
Plugins seem to not be working on flipper 0.72.0

### ISSUE THREAD

**Issue by erikeelde** [blankapp/flutter_flipperkit#33]
I just recently installed the latest version of flipper (zip download on ubuntu) and the dbbrowserplugin no longer worked. As the logs were complaining about the plugin reporting the wrong name for the plugin I decided to try reinstalling the dbbrowser plugin and now I can not install it anymore. 
It does appear in the list of plugins and when I click install it prompts me to restart flipper desktop (all seems well). and when flipper launches back up the plugin is reported as not installed still. 

I think the same thing is happening to the redux plugin - but I wasn't actively using it so can't report on the behavior on that plugin.

**Comment by erikeelde** [comment]
Confirmed to still be an issue on flipper desktop 0.74.0. 

Above mentioned complaints about the wrong name is specifically:  

`Plugin name mismatch: Package 'flipper-plugin-dbbrowser' exposed a plugin with id 'DatabaseBrowser'. Please update the 'package.json' to match the exposed plugin id`

**Comment by erikeelde** [comment]
Worked for a colleague but I'm stuck with the plugin being removed when launching flipper desktop.

On linux:
`~/.flipper/installed-plugins/flipper-plugin-dbbrowser/1.0.3/package.json`

Change id from `flipper-plugin-dbbrowser` to `DatabaseBrowser`:
```
{
  "$schema": "https://fbflipper.com/schemas/plugin-package/v2.json",
  "name": "flipper-plugin-dbbrowser",
  "id": "DatabaseBrowser",
  "version": "1.0.3",
  "description": "Database Browser for flipper",
  "main": "dist/bundle.js",
  "flipperBundlerEntry": "index.js",
  "license": "MIT",
  "keywords": [
    "flipper-plugin"
  ],
  "icon": "database",
  "title": "Database Browser",
  "bugs": {
    "email": "lijy91@foxmail.com"
  },
  "peerDependencies": {
    "flipper": "latest"
  },
  "devDependencies": {
    "flipper": "latest",
    "flipper-pkg": "latest"
  },
  "scripts": {
    "prepack": "flipper-pkg lint && flipper-pkg bundle"
  }
}

```

**Comment by lijy91** [comment]
Update to `0.0.25`

```yaml
dependencies:
  flutter_flipperkit: ^0.0.25
```
