### ISSUE TITLE
Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions

### ISSUE THREAD

**Issue by mohammed-akl** [blankapp/flutter_flipperkit#40]
while running on android device Flipper log shows "Watchman:  Watchman was not found in PATH.  See https://facebook.github.io/watchman/docs/install.html for installation instructions"

**Comment by mohammed-akl** [comment]
and also, showing No application selected

**Comment by lijy91** [comment]
Please try to install `watchman` and configure it
