### ISSUE TITLE
symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by tiennguyen9988** [blankapp/flutter_flipperkit#42]
<img width="1680" alt="Screen Shot 2021-06-20 at 20 13 49" src="https://user-images.githubusercontent.com/3782474/122675556-26f19200-d204-11eb-8139-80678e98025a.png">

**Comment by lijy91** [comment]
I am developing [AnyInspect](https://github.com/anyinspect/anyinspect_app) to replace Flipper, `flutter_flipperkit` will stop updating in the near future.

[![Discord](https://img.shields.io/badge/discord-%237289DA.svg?style=for-the-badge&logo=discord&logoColor=white)](https://discord.gg/X2Gcce3Q)
