### ISSUE TITLE
Conflict with other dependencies

### ISSUE THREAD

**Issue by Izudinalqasam** [blankapp/flutter_flipperkit#44]
I get error when following setup for IOS 

` The Swift pod `DKPhotoGallery` depends upon `SDWebImage`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies`

when i change it to be 
```
target 'Runner' do
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
```

install pod successful but when i run project to simulator i get  another error
<img width="234" alt="Jepretan Layar 2021-07-22 pukul 23 19 41" src="https://user-images.githubusercontent.com/31473636/126673457-64b55c92-46c6-402a-9d51-cb583ffa614c.png">

**Comment by Jparrgam** [comment]
@lijy91 Do you have any idea of ​​this compilation error, I have the same error in android 

`> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Type com.facebook.soloader.SoLoader is defined multiple times: /Users/x/Documents/picap/picap_flutter/build/flipper-no-op/.transforms/77889fe50da36fe0517a5c6ad12f9211/classes/classes.dex, /Users/x/Documents/picap/picap_flutter/build/app/intermediates/external_libs_dex/gmsRelease/mergeExtDexGmsRelease/classes.dex
`

**Comment by lijy91** [comment]
I am developing [AnyInspect](https://github.com/anyinspect/anyinspect_app) to replace Flipper, `flutter_flipperkit` will stop updating in the near future.

[![Discord](https://img.shields.io/badge/discord-%237289DA.svg?style=for-the-badge&logo=discord&logoColor=white)](https://discord.gg/X2Gcce3Q)
