### ISSUE TITLE
HttpClient的签名发生了改变

### ISSUE THREAD

**Issue by ykrank** [blankapp/flutter_flipperkit#45]
`lutter_flipperkit-0.0.27/lib/plugins/network/flipper_http_client.dart:101:28: Error: A value of type 'Future<bool> Function(Uri, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(Uri, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
 - 'Uri' is from 'dart:core'.
    client!.authenticate = f;

flutter_flipperkit-0.0.27/lib/plugins/network/flipper_http_client.dart:118:33: Error: A value of type 'Future<bool> Function(String, int, String, String)?' can't be assigned to a variable of type 'Future<bool> Function(String, int, String, String?)?' because 'String?' is nullable and 'String' isn't.
 - 'Future' is from 'dart:async'.
    client!.authenticateProxy = f;`

**Comment by lijy91** [comment]
已修复，请升级到 `0.0.28`

```yaml
dependencies:
  flutter_flipperkit: ^0.0.28
```
