### ISSUE TITLE
Error running pod install Error

### ISSUE THREAD

**Issue by phattranky** [blankapp/flutter_flipperkit#7]
<img width="987" alt="Screen Shot 2019-05-19 at 10 37 32 AM" src="https://user-images.githubusercontent.com/6443154/57977415-609eb000-7a22-11e9-99b4-3d388f9dab83.png">

I got this error after add this plugin to dependencies of `pubspec.yaml` and call `flutter packages get`

<img width="635" alt="Screen Shot 2019-05-19 at 10 41 33 AM" src="https://user-images.githubusercontent.com/6443154/57977430-b6735800-7a22-11e9-878f-58eb4ca7f9af.png">

I'm not implement anything in MainApp.

I try to clean the Pod and re-install as well. What should I do?

**Comment by lijy91** [comment]
You need change your project `ios/Podfile` file according to the example:

```diff
# Uncomment this line to define a global platform for your project
-# platform :ios, '8.0'
+platform :ios, '9.0'
```

https://github.com/blankapp/flutter_flipperkit#installation
