### ISSUE TITLE
Android dependency 'androidx.appcompat:appcompat' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath

### ISSUE THREAD

**Issue by jefferybai** [blankapp/flutter_flipperkit#9]
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:preDebugBuild'.                         
> Android dependency 'androidx.appcompat:appcompat' has different version for the compile (1.0.0-rc01) and runtime (1.0.0) classpath. You should manually set the same version via DependencyResolution
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org

**Comment by lijy91** [comment]
You need update `gradle-tools` to 3.3.0+

Please see: https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility
